name: Run Jupyter Notebook Daily

on:
  push:
  schedule:
    - cron: '0 7 * * *'  # Run at 8:00 AM in your local time zone (CET)
    - cron: '0 11 * * *'  # Run at 12:00 PM (midday) in your local time zone (CEST)

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Adjust the Python version if needed

    - name: Install dependencies
      run: |
        pip install jupyter
        pip install pandas
        pip install numpy
        pip install matplotlib
        pip install requests
        pip install beautifulsoup4
        pip install wordcloud
        pip install nltk
        pip install scikit-learn

    - name: Download NLTK resources
      run: |
        python -c "import nltk; nltk.download('stopwords')"
        python -c "import nltk; nltk.download('punkt')"

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --execute NLP/Scraping/WebScraping.ipynb --to notebook --inplace

