name: Run Jupyter Notebook Daily

on:
  push:
  schedule:
    - cron: '0 7 * * *'  # Run at 8:00 AM in your local time zone (CET)
    - cron: '0 11 * * *'  # Run at 12:00 PM (midday) in your local time zone (CEST)

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Adjust the Python version if needed

    - name: Install dependencies
      run: |
        pip install jupyter
        pip install pandas
        pip install numpy
        pip install matplotlib
        pip install requests
        pip install beautifulsoup4
        pip install wordcloud
        pip install nltk
        pip install scikit-learn

    - name: Download NLTK resources
      run: |
        python -c "import nltk; nltk.download('stopwords')"
        python -c "import nltk; nltk.download('punkt')"

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --execute NLP/Scraping/WebScraping.ipynb --to notebook --inplace

    - name: Save Word Cloud Image
      run: |
        # Your code for generating the word cloud image goes here
        # Replace this with your word cloud generation code

        # Save the word cloud image in the 'clouds' directory
        todayDate = datetime.today().strftime('%Y-%m-%d-%H%M%S')
        image_path = "clouds/" + todayDate + "_wordcloud.png"
        plt.savefig(image_path, dpi=300)

    - name: Upload Word Cloud Image Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wordcloud-image
        path: clouds  # The directory where the word cloud image is saved
